### PR TITLE
Integration/1.8.0

### PR DESCRIPTION
**Pull request by pccowboy**
[VME-1568] Merge in upstream terraform-provider-aws release 1.8.0

Merge commit '8937a3a4e9d77c8089cf147861b604e3a2d8cf7e' into integration/valimail_aws_provider

### CODE REVIEW

**Comment by dweinand** [comment]
I'm confused by this. I would expect that we'd be re-cutting our integration branch from upstream and then layering our changes on top. This approach seems ripe for problems.

**Comment by dweinand** [comment]
@pccowboy Did you see my concern here?

**Comment by pccowboy** [comment]
I did, sorry I did not comment sooner.  I am recutting the integration branch as you suggest, and then layering the coveo/new-ssm-parameters-features branch and our two branches (bug-correct-source-region and feature/add_valimail_circleci) on top.

**Comment by pccowboy** [comment]
I'm going to close this PR, and reopen with the new branch.

**Pull request closed without merging**
